### ISSUE TITLE
Could you find offsets for iphone 13, 16.6 beta 1?

### ISSUE THREAD

**Issue by x3n1al** [34306/kfd_offsets#2]
I can provide files, just need a guide to get them

**Comment by 34306** [comment]
Send me your kernelcache

**Comment by x3n1al** [comment]
assuming its the file inside the ipsw i used to restore
i added .zip to it so i can send through github
[kernelcache.release.iphone7.zip](https://github.com/34306/kfd_offsets/files/12183775/kernelcache.release.iphone7.zip)

**Comment by 34306** [comment]
> assuming its the file inside the ipsw i used to restore
> i added .zip to it so i can send through github
> [kernelcache.release.iphone7.zip](https://github.com/34306/kfd_offsets/files/12183775/kernelcache.release.iphone7.zip)

are you sure that's iOS 16.6b1?

Log error:
Inited machopatchfinder64 143 ab2d635e1cd0c51ae6e7ff1d2bfa2b6af9bdeee7
Kernel version: 4903.272.5~1
Detected iOS 12 kernel
[Error] liboffsetfinder64: failed with exception:
[exception]:
what=not implemented by provider
code=8847375
line=135
file=patchfinder.cpp
commit count=143
commit sha  =ab2d635e1cd0c51ae6e7ff1d2bfa2b6af9bdeee7

**Comment by x3n1al** [comment]
OOPS WRONG IPSW SORRY
heres the actual one
[kernelcache.release.iphone14.zip](https://github.com/34306/kfd_offsets/files/12184143/kernelcache.release.iphone14.zip)

**Comment by 34306** [comment]
Please check the repo, I updated it!

**Comment by x3n1al** [comment]
tysm
