### ISSUE TITLE
Any chances to get Kfd working on iPhone XR 16.6 B1?

### ISSUE THREAD

**Issue by oxGorou** [34306/kfd_offsets#3]
I'm tested the Xr offsets from this [repo](https://github.com/Lrdsnow/kfd_offsets) and it's doesn't works 👀

**Comment by oxGorou** [comment]
Hey i tried the latest offsets for 16.6 Beta 1 (IPhone XR) and it's call back me these result:
![Screenshot 2023-07-31 at 08 01 50](https://github.com/34306/kfd_offsets/assets/98001973/31d87650-01f9-45ef-a9bd-01295065a514)

**Comment by oxGorou** [comment]
![image](https://github.com/34306/kfd_offsets/assets/98001973/dad49467-d7f0-4d1a-bc69-b4623a71c1c0)

**Comment by oxGorou** [comment]
@34306

**Comment by 34306** [comment]
Ya lrdsnow note that it should work so it's just work

**Comment by oxGorou** [comment]
so can you combine it to your stuffs? because idk how to make tweaks with that.

**Comment by 34306** [comment]
> so can you combine it to your stuffs? because idk how to make tweaks with that.

I'll, but not now.
